# Use Node.js LTS as base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Build the React applicatio

# Use nginx to serve the built app
FROM nginx:stable-alpine


# Expose the frontend port
EXPOSE 8080

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
